cesanta/docker_auth

- auth_server/server/config.go
- examples/reference.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/8)
> Add goole_auth.client_secret_file

- auth_server/main.go
- auth_server/server/config.go
This PR allows running the auth server as http:// instead of https://.  Our use-case is that we prefer to configure https at the ELB level, not at the internal node level.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/25)
> Allow non tls server

- auth_server/Dockerfile
- auth_server/authn/ldap_auth.go
- auth_server/server/config.go
- auth_server/server/server.go
- examples/ldap_config.yml
Signed-off-by: Lin Qing <qing.lin@hp.com>
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/27)
> support ldap authentication

- auth_server/authn/ldap_auth.go
- examples/ldap_auth.yml
Make InsecureSkipVerify default to false
Fixes #37
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/48)
> Support different TLS methods for LDAP

- auth_server/authz/acl.go
- auth_server/authz/acl_test.go
- auth_server/authz/authz.go
- auth_server/main.go
- auth_server/server/server.go
- examples/reference.yml
Fixes #49
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/50)
> Add IP matching to ACL

- README.md
- auth_server/Makefile
- auth_server/authn/mongo_auth.go
- auth_server/authz/acl_mongo.go
- auth_server/mgo_session/mgo_session.go
- auth_server/server/config.go
- auth_server/server/server.go
- docs/Backend_MongoDB.md
- examples/reference.yml
I've expanded the MongoDB support to include a collection for authentication.  This includes a refactor of mgo sessions and the associated structs to a separate package. I've also implemented the Copy->Close flow for sessions as recommended in the mgo docs.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/55)
> Mongo authn

- auth_server/authz/acl_mongo.go
- docs/Backend_MongoDB.md
Without this you are often forced to delete/recreate records to manipulate natural ordering which is not feasible in large deployments.
Example results from my dataset:
Given: ``sort_keys: ["priority", "Comment"]``
Natural order:
```golang
[
{"Match":{"account":"admin"},"Actions":["*"],"Comment":"Priority 2"}
{"Match":{"account":"/.+/","name":"${account}/*"},"Actions":["*"],"Comment":"Priority 1"}
{"Match":{"account":"/.+/","name":"${account}/*"},"Actions":["*"],"Comment":"Apriority 1"}
{"Match":{"account":"/.+/","name":"${account}/*"},"Actions":["*"],"Comment":"priority none"}
{"Match":{"account":"admin"},"Actions":["*"],"Comment":"APriority 0"}
]
```
Sorted order:
```golang
[
{"Match":{"account":"/.+/","name":"${account}/*"},"Actions":["*"],"Comment":"priority none"} …
```
> Add optional sort_keys field for ACLs.

- auth_server/server/server.go
Fixes #67
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/68)
> Add support for multiple scopes

- auth_server/authn/mongo_auth.go
- auth_server/authz/acl_mongo.go
This fixes #71 
Whenever we get a io.EOF error from our mongo calls we will wait a second and retry the call. I was able to watch both ACL and auth attempts work without interruption during a failover event.
Note that there is no need to do anything to refresh our connection. mgo automatically updates the connection on a EOF.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/79)
> Retry connection to mongo when we get a EOF error.

- examples/reference.yml
Closes Issue #69
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/87)
> use correct username key for mongo dial

- examples/ldap_auth.yml
- examples/reference.yml
Fixes Issue #73
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/89)
> update ldap docs.

- auth_server/server/config.go
- auth_server/server/server.go
- examples/reference.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/91)
> Add server.real_ip_header

- auth_server/.gitignore
- auth_server/Makefile
- auth_server/gen_version.py
- auth_server/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/110)
> Version-tag builds

- auth_server/authn/authn.go
- auth_server/authn/data/github_auth.tmpl
- auth_server/authn/github_auth.go
- auth_server/authn/google_auth.go
- auth_server/authn/tokendb.go
- auth_server/server/config.go
- auth_server/server/server.go
- examples/reference.yml
~~This is not fully functional yet in my tests…~~
~~Because GitHub tokens do not expire, I am currently just storing it forever. We might want to set a static expiration time in config though.~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/115)
> Add GitHub authn provider

- auth_server/authn/authn.go
- auth_server/authn/data/github_auth.tmpl
- auth_server/authn/github_auth.go
- auth_server/authn/google_auth.go
- auth_server/authn/tokendb.go
- auth_server/server/config.go
- auth_server/server/server.go
- examples/reference.yml
This is a new PR like #115, but squashed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/119)
> GitHub authn

- examples/reference.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/120)
> Add missing "organization" example to reference.yml

- README.md
- auth_server/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/123)
> update ldap docs in README - #111

- auth_server/authz/acl.go
- auth_server/authz/acl_test.go
- examples/reference.yml
try fix #45
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/124)
> enable capture group aware variable replacement

- examples/reference.yml
#130
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/133)
> Clarify the purpose of token.certificate and key

- auth_server/server/server.go
Should fix #129
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/132)
> Fix parsing of scope

- auth_server/server/server.go
Fixes #146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/147)
> Allow empty scope

- auth_server/authn/ldap_auth.go
Should fix https://github.com/cesanta/docker_auth/issues/62
Related to https://github.com/cesanta/docker_auth/issues/37#issuecomment-161865181 and https://github.com/golang/go/issues/7342
For some reason, I get the following error, but that may be because I am trying to build master. Some futher insight is welcome. Should not be related to my change.
EDIT: After applying my patch to tag `1.2`, this builds cleanly.
```
F0205 02:16:59.049221    8077 main.go:171] Failed to load config: could not parse config: yaml: unmarshal errors:
line 28: cannot unmarshal !!str `` into *authn.PasswordString
```
Any feedback is welcome.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/16 …
> Add ServerName to tlsConfig when InsecureSkipVerify is false

- auth_server/server/config.go
- auth_server/server/server.go
- examples/reference.yml
Usable when service is behind a proxy.
Tested with docker-distribution and apache httpd.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/185)
> Feature: URL Prefix support (#181)

- auth_server/authn/mongo_auth.go
mongo auth will now include labels when they are part of an authenticated user's record.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/194)
> Return labels from mongo users

- auth_server/authz/acl.go
- auth_server/authz/acl_test.go
- auth_server/vendor/vendor.json
- docs/Backend_MongoDB.md
- docs/Labels.md
- examples/reference.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/195)
> Add matching of label placeholders

- auth_server/authn/static_auth.go
- docs/Labels.md
Fixes #202
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/206)
> Fix Static labels and document supported backends

- auth_server/mgo_session/mgo_session.go
- examples/reference.yml
Fixes #205
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/207)
> Allow MongoDB connections to use TLS

- docs/Backend_MongoDB.md
Fixes #213
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/214)
> Update example mongo rule order

- examples/non_tls.yml
Adds an example config for #25.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/209)
> Add a non-tls example config

- auth_server/README.md
It wasn't obvious how to get deps locally until reading the makefile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/233)
> doc: mention make deps in auth_server README

- README.md
- docs/auth-methods.md
Followup from https://github.com/cesanta/docker_auth/pull/219
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/234)
> docs: quick setup steps for github auth

- auth_server/server/server.go
Signed-off-by: duyanghao <1294057873@qq.com>
> return 401 when there is no user or password

- examples/simple.yml
Signed-off-by: duyanghao <1294057873@qq.com>
> fix simple.yaml example: replace user with test

- auth_server/server/server.go
As it is right now, it is not possible to authenticate plugin requests using `docker-auth`. The docker distribution registry expects[0] a scope with `Type` repository and `docker-auth` is sending `repository(plugin)` as that's what it receives in the request.
Instead of sending `repository(plugin)` we should be sending `repository` and setting the scope class to `plugin`. The default class is `image`, which is why this works fine right now.
I had trouble finding a detailed documentation about how the docker registry uses `class` but here's a test:
```curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository(plugin):rchicoli/docker-log-elasticsearch:pull,push"```
The above command produces a token that contains the following access request (you can decode the token …
> Send the scope class as part of the token

- auth_server/Makefile
> fix: segmentation fault on arm64 image

- README.md
- auth_server/authn/data/gitlab_auth.tmpl
- auth_server/authn/data/gitlab_auth_result.tmpl
- auth_server/authn/gitlab_auth.go
- auth_server/authn/tokendb_redis.go
- auth_server/server/config.go
- auth_server/server/server.go
- examples/reference.yml
Hey there!
This pull request is represented by 1 commit where I've added the Gitlab authentication method.
I thing it is important for that organizations who are using Gitlab as a version control system.
> feat: Added Gitlab Authentication method

- auth_server/authn/data/gitlab_auth.tmpl
Added the link for sign-in to the gitlab for the better visibility.
> bugfix: Added sign-in link under gitlab page template

- auth_server/authz/acl_xorm.go
> added xorm JSON struct tag to XormACLEntry

- auth_server/authn/data/gitlab_auth_result.tmpl
- auth_server/authn/data/oidc_auth_result.tmpl
I missed that there were three results pages so this replicates #384 for the other two.
> Replicate #384 for GitLab and OIDC

- auth_server/authz/acl.go
https://github.com/cesanta/docker_auth/issues/394
> fixed leaking goroutines
