auth_server/server/google_auth.go

Looks like tokeninfo endpoint won't do that for us, as I mistakenly
thought.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/9)

Verify token expiration time

---

auth_server/main.go
auth_server/server/google_auth.go
auth_server/server/server.go
auth_server/server/static_auth.go

Server will watch its config and restart on change.
Care is taken not to restart when config file is obviously bad
(this won't catch all the errors though).
Case where file goes missing and reappears is also handled gracefully.
Restarting on signal is not implemented because it's not necessary:
sending a signal tells the server that the file has changed. In this
case server watches the file and does not need to be told about it.
Closes #6
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/13)

Implement config reload

---

README.md
auth_server/authn/authn.go
auth_server/authn/bindata.go
auth_server/authn/google_auth.go
auth_server/authn/static_auth.go
auth_server/authz/acl.go
auth_server/authz/authz.go
auth_server/authz/set.go
auth_server/server/config.go
auth_server/server/server.go
examples/reference.yml
examples/simple.yml

Since 1.8 Docker will always request push and pull actions (scopes),
and we should return the subset that is allowed.
Fixes #22
docker/docker#15640
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/23)

Auth{n,z} refactor; fix token generation for 1.8

---

auth_server/authz/acl.go
examples/reference.yml

a cleanup of #24
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/26)

Add support for variables of authrequestinfo in the ACL of the config file

---

auth_server/main.go

SSLv3 is broken but is still enabled in crypto/tls.  Docker Registry 2.1 has already implemented a workaround, so we should follow their lead here.  See https://github.com/docker/distribution/commit/dc5869de0b4fcab4f0291c8e835560951c5e968a
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/28)

Disable broken SSLv3 and force strong ciphers to match Docker Registry 2.1 security

---

auth_server/authn/ldap_auth.go

Makes it editor-friendly.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/34)

Trim space from LDAP password before use

---

auth_server/authz/acl.go
examples/reference.yml
examples/simple.yml

When ACLs are stored outside of the static YAML configuration file one
might be interested in a context about the ACL.
I proposed a database (e.g. MongoDB) ACL backend in #38 and that's why I
need the comment field on an ACL.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/42)

Add comment field to ACLs

---

auth_server/authz/acl.go
auth_server/authz/acl_mongo.go
auth_server/main.go
auth_server/server/config.go
auth_server/server/server.go
docs/ACL_Backend_MongoDB.md
examples/reference.yml

This adds the ability to store ACLs in a MongoDB database. There's also
a documentation file in `docs/ACL_Backend_MongoDB.md` that explains the
document layout inside MongoDB.
See also #38 for the initial discussion on this topic.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/44)

Add MongoDB backend for ACLs

---

README.md
auth_server/.gitignore
auth_server/Dockerfile
auth_server/Makefile
auth_server/main.go

This switches this to use golang-builder to make it a bit easier for switching between OSX and Linux.
I also added some commands to the Makefile to make some things more configurable, made /config/config.yml the default location to look for configs.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/46)

Make image name configurable, use golang-builder, compress bin

---

auth_server/Makefile

This makes it much easier to rebuild the project by itself if you don't need updated deps or the full image
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/54)

move docker-build outside of normal build target

---

auth_server/authn/mongo_auth.go

Sorry for the deluge of commits. Adding the index to acls made me realize that we should enforce uniqueness of the users collection as well.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/65)

Enforce index in users collection

---

auth_server/server/config.go

Hello,
I updated the config struct to ommit ACLMongo if empty, to avoid having `ACLMongo:  null` on serialization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/70)

Make ACLMongo omitempty for serialization

---

examples/reference.yml

This took me a good deal of effort to figure out (thanks for your suggestions in other threads about `-v 2`). I figured I'd kick back what worked for me in the event it helps same someone else in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/81)

example acl for catalog

---

auth_server/authn/ldap_auth.go

It's kind of expected, we should return 403 in this case and not 500.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/104)

Handle "invalid credentials" as a non-error

---

auth_server/authn/ldap_auth.go

The LDAP authn provider currently returns no error when the user is not found in LDAP.
For this reason, it fails authentication without checking the next authenticator, which is a wrong behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/114)

Return NoMatch when user does not exist in LDAP

---

examples/reference.yml

If you as HTTP, your browser will simply download a blob...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/121)

Add 'as HTTPS' to Google/GitHub doc

---

auth_server/server/config.go
auth_server/server/server.go
examples/reference.yml

Going to submit a few PRs for stuff we've found useful.
Currently the real IP header functionality defaults to grabbing the first IP address.  This would put responsibility of protecting the header upstream.  By adding a position argument I can easily select the trusted position of the header.
For example, we have this behind a google load balancer which provides the client IP for us in `X-Forwarded-For`: https://cloud.google.com/compute/docs/load-balancing/http/
The load balancer provides a header in the format of: `X-Forwarded-For: <client IP(s)>, <global forwarding rule external IP>`
Something like `X-Forwarded-For: 104.196.118.51, 130.211.9.23` is received where `104.196.118.51` is the client IP, `130.211.9.23` is the load balancer IP.
Now let's say that I attempt to spoof the header …

Add positional argument for real ip header.

---

auth_server/authn/authn.go
auth_server/authn/ext_auth.go
auth_server/authn/github_auth.go
auth_server/authn/google_auth.go
auth_server/authn/ldap_auth.go
auth_server/authn/mongo_auth.go
auth_server/authn/static_auth.go
auth_server/authz/acl.go
auth_server/authz/acl_test.go
auth_server/authz/authz.go
auth_server/main.go
auth_server/server/config.go
auth_server/server/server.go

Add labels that can be passed from authentication to authorization rules.
Add ability to match them:
```
acl:
- match: {labels: {"foo": "bar", "baz": "/quux.*/"}}
```
All the label expressions must match ("and" logic on label expressions).
Labels are a string -> []string map, so a label can have multiple values
and all of them will be tried during matching, but only one is required
("or" logic on label values).
For now, only external authenticator can add labels, but in the future
e.g. GitHub authn can pass down GH organizations or teams the user
belongs to (should help #117).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/139)

Auth labels

---

auth_server/authz/acl_ext.go
auth_server/authz/ext_authz.go
auth_server/server/config.go
auth_server/server/server.go
examples/reference.yml

PR for #142 
Added support to authorize request via an external script. The script returns a simple yes/no for the authz request through exit codes similarly to `ext_auth`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/143)

Support for external authorization

---

auth_server/authn/ldap_auth.go

See: go-ldap/ldap#93
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/155)

ldap_auth: An empty password worked for any valid user

---

auth_server/authn/data/github_auth.tmpl
auth_server/authn/github_auth.go
examples/reference.yml

Hey, based on #135 and @rojer `gh` branch I tried to enhance the solution. 
I think that it's way easier to split the Github API URI (needed for fetching user and org details from GH) and the Github Web URI (needed for the OAuth-Flow).   
github.com still remains the default. I also modified the github html template. 
Full disclosure: I am certainly no expert in Go (in fact, it's my first Go contribution). 
Please have a look and let me know whether this fits the needs or not. In the meantime, I am going to test it. 
Cheers,
Jan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/151)

Feature: GHE Support

---

examples/ext_auth.sh

using the ext_auth example script in the `stable` image  
docker logs will always show `files not exist` error  
replace the `#!/bin/bash` by `#!/bin/sh` will fix this problem
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/159)

fix the "file not exist" problem

---

auth_server/authn/github_auth.go
auth_server/authn/google_auth.go

Ref.: https://github.com/cesanta/docker_auth/issues/157
Say `docker login YOUR_REGISTRY_FQDN` as a quick n dirty fix so the user knows that he should set its registry url.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/158)

Quick fix so user knows that he should set registry fqdn

---

README.md

In text the link to the container was cesanta/docker, while it should (have) been cesanta/docker_auth
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/164)

Fixed simple mistake in README

---

auth_server/authz/acl.go
auth_server/authz/acl_test.go

There is `service` field to define in the ACL, however the code misses to check it.
This PR fixes this so you can have the rules like this:
```
- match: {account: "", service: "notary.quiq.sh"}
actions: ["pull"]
comment: "Anonymous users can get signatures from notary."
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/170)

Fix checking of service field in ACL.

---

auth_server/authn/data/github_auth.tmpl

The read:org scope is required for the authorization as it allows user to check whether it's a member of the organization or not.
GitHub Scopes for OAuth Apps are described:
https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-scopes-for-oauth-apps/
Fixes #189
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/190)

docker_auth/github: pass read:org scope for the authorization

---

examples/reference.yml

When using the Google or GitHub (or really any) OAuth method, the browser you use cannot have third party cookies blocked. If they are, the authentication will fail and it will feel as if the calls are going to the wrong places. 
This commit adds a little note in the configuration, so it's immediately apparent to the developer testing their setup. In other words, this would have saved me an hour 😉 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/187)

Add a Note regarding OAuth and Third-Party Cookies

---

examples/reference.yml

Added label usage examples in the reference.yml.
Fixes #188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/192)

doc: document label usage in reference.yml

---

auth_server/authn/github_auth.go
auth_server/authn/tokendb.go
auth_server/authn/tokendb_gcs.go
auth_server/server/config.go
auth_server/vendor/vendor.json
examples/reference.yml

Added a new implementation of TokenDB that uses Google Cloud Storage as backend for storing of the tokens.
This makes container independent from the file system of the container or from the target system and is good alternative to mounted clustered file systems to container.
Docs examples are updated regarding this change as specifying token_db configuration now becomes alternate between local file and gcs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/193)

docker_auth/github: store tokens in google cloud storage

---

auth_server/authn/ldap_auth.go
examples/ldap_auth.yml
examples/reference.yml

Sometimes the signing CA for LDAP is not in the certs directory golang looks into, this PR provides support for using a custom filepath to load the CA to verify the LDAP cert.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/197)

Set custom CA certificate for ldap cert verification

---

auth_server/authz/acl.go
docs/Labels.md

This small change allows for access changes to potentially be 100% user based when using labels to match names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/199)

Stop quoting meta chars in labels

---

auth_server/main.go

Modern Go versions (1.9 and 1.10) as of this commit are much better
about cipher suite selection and the ssl/tls protocols used. In fact,
SSLv3 needs to be explicitly enabled now.
Fixes: https://github.com/cesanta/docker_auth/issues/231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/232)

drop old hardcoded configs around TLS 1.x

---

auth_server/authn/tokendb.go

This patch extends the `TokenDBValue` struct in order to allow storing "labels" associated
with a user directly in the data structure, ie. without a need for secondary storage for lookup.
I'm aware that this changes a core entity, but we haven't found a simpler and non-invasive way of doing that, when working on the possibility of using Github teams as "labels" in the ACL configuration.
We think that it simplifies the workflow for anybody who would like to use a similar mechanism for authentication and authorization — after all, the amount of data to store in the token is very small, basically an array of strings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/217)

Add the `Labels` property to the `TokenDBValue` struct

---

auth_server/authn/bindata.go
auth_server/authn/data/github_auth_result.tmpl
auth_server/authn/github_auth.go
examples/reference.yml

*** NOT READY TO MERGE ***
This pull request depends on https://github.com/cesanta/docker_auth/pull/219 and significantly improves the usability of the Github authentication workflow, by displaying a complete `docker login` command on the result page (ie. including the repository hostname), when a `registry_url` value is set in the configuration YAML.
The only significant commit is 9ba3328, and the branch has to be rebased before merging it, since the three other commits are redundant — this was the only way we could keep separate branches for the "github teams" and "redis tokendb" features isolated in our repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/221 …

Improve the `docker login` instructions for Github authentication

---

auth_server/README.md

The previous instructions:
- leave the source code in the wrong place to be build
- omit one of the steps
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/242)

Fix broken build instructions

---

auth_server/authn/ldap_auth.go
examples/reference.yml

Since the original PR went stale, I
* Cherry-picked the commits from https://github.com/cesanta/docker_auth/pull/167 so they apply against master again. 
* Added example ACL as requested
@rojer @alonbl Please have another look. Also @kcd83 fyi :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/docker_auth/228)

MAP LDAP account attributes to labels such as groups

---

auth_server/authn/ldap_auth.go

A follow up to https://github.com/cesanta/docker_auth/pull/228#issuecomment-389545187 comment:
> FreeIPA seems to have types of DN elements lowercased
In this PR we transform DN attributes to upper case (as in most cases they are already uppercased, so it looks like it's more optimal then lowercasing) and compare to `"CN"`.

Add support for lowercases DN elements

---

auth_server/main.go
auth_server/server/config.go
auth_server/server/server.go
examples/reference.yml

This PR extends the server's TLS configuration. While the default TLS settings should be enough for most use cases, if you get a bit paranoid about security you'd probably want to tweak things a bit. This PR allows that.
The motivation in my case is passing the FedRAMP certification, which required some TLS vulnerabilities to be addressed. Here's a FedRAMP compliant (as of Sep 5th, 2019) configuration example:
```yaml
server:
addr: :5001
certificate: /path/to/server.pem
key: /path/to/server.key
hsts: true
tls_min_version: 0x0303
tls_curve_preferences:
- 25
- 24
- 23
tls_cipher_suites:
- 0x009c
- 0x009d
- 0xc02f
- 0xc02b
- 0xc030
- 0xc02c
- 0xcca8
- 0xcca9
```
If you're curious I used [this tool](https://github.com/drwetter/testssl.sh) to test both the current server and the patched one …

feat: extended TLS configuration

---

auth_server/server/server.go

I've been trying to get containerd and cesenta to play nice in terms of authentication. After some digging I found out authentication doesn't work because containerd is
- doing POST requests during authorization with username/password in the formdata instead of Basic Authentication and docker_auth doesn't recognise this. 
- the JSON that is responded with holds the token in `token` where the oAuth specification tells me it should be `access_token`.
At first I patched this in containerd itself (https://github.com/containerd/containerd/pull/3795) but the devs over there convinced me they are following the spec and docker_auth should be fixed. So that's what this PR is trying to achieve and I think it's fully backwards compatible. 
Below is the output before and after the patch, when I run: …

Improve oAuth compatibility

---

auth_server/authn/github_auth.go
auth_server/authn/tokendb_redis.go
auth_server/go.mod
auth_server/go.sum
auth_server/server/config.go
examples/reference.yml

This pull request adds a new type, `redisTokenDB`, which implements a token storage based on [_Redis_](https://redis.io).
The primary motivation is to allow the authentication server to run in a distributed environments, with multiple instances of the server proxied by a load balancer. The default file-based implementation is insufficient in such a scenario, because each server would have its own database of tokens, and the Google Cloud Storage-based implementation is prohibitive when the service would run eg. on AWS, due to latency issues.
The Redis-based implementation can work with a single Redis instance or a Redis Cluster — the corresponding client is selected based on the YAML configuration, where the user provides either a single `url` value as a string, or one or more `urls` as an …

Add a Redis-based token storage implementation

---

auth_server/server/server.go

This change is necessary to support older clients. #272

Returning the "token"-field

---

auth_server/server/server.go

Per
https://docs.docker.com/registry/spec/auth/scope/#resource-scope-grammar
and https://docs.docker.com/registry/spec/auth/oauth/
multiple scopes are separated by a single space within a single `scope`
parameter.
This fixes compatibility with buildkit which currently generates a bad request when pushing:
``` sh
W0306 15:29:11.332525      31 server.go:424] Bad request: invalid scope: "repository:my-registry.com/my-repo:pull repository:my-registry.com/my-repo:pull,push"
```

Fix scope parsing

---

README.md

Really just a tiny documentation fix, but the Docker Hub link in the README.md currently points to a wrong URL, leading the reader to an empty page.

Fix Docker Hub link in README.md

---

auth_server/Makefile
auth_server/gen_version.py

This fixes the `build-release` target. The builder image is based on alpine, which as of 3.12 no longer includes `py2-pip`.

Move to Python3

---

auth_server/authz/acl.go
auth_server/authz/acl_test.go

Recent Go updates cause test failures when there are issues found via `go vet`, including `fmt.Printf`-based misuse.
This is causing `go test ./...` to fail on `master`:
```
$ go test ./...
authz/acl.go:117:4: Infof format %s has arg e.Comment of wrong type *string
authz/acl_test.go:52:4: Errorf format %q has arg c.mc of wrong type github.com/cesanta/docker_auth/auth_server/authz.MatchConditions
authz/acl_test.go:54:4: Errorf format %q has arg c.mc of wrong type github.com/cesanta/docker_auth/auth_server/authz.MatchConditions
?   	github.com/cesanta/docker_auth/auth_server	[no test files]
?   	github.com/cesanta/docker_auth/auth_server/api	[no test files]
ok  	github.com/cesanta/docker_auth/auth_server/authn	0.091s
FAIL	github.com/cesanta/docker_auth/auth_server/authz [build failed]
? …
```

Fix go vet failures

---

.github/workflows/go_test.yml

As promised go tests are now run by Github Actions
Future enhancements could include linting.

Add Github actions for go tests

---

.github/workflows/docker-nightly.yml

Before merging two github action secrets will need to be added:
`DOCKER_USERNAME`
`DOCKER_PASSWORD`
Whichever user is used will need to have write permissions to the docker image.
Another PR coming soon which will support git tags -> docker image tags
Fix #288

Docker nightlies

---

auth_server/Makefile

Hi,
I tried to run the build-release target but I was not successful. The image stopped with an error:
```
authn/authn.go:19: running "go-bindata": exec: "go-bindata": executable file not found in $PATH
make: *** [Makefile:17: generate] Error 1
```
With this PR, the go-binddata tool is installed as described in [https://github.com/go-bindata/go-bindata#installation](https://github.com/go-bindata/go-bindata#installation).

Install go-binddata as a global binary

---

auth_server/server/server.go

Hi!
Thanks for your awesome project!
I tried to use this project in an IPv6 infra, behind a reverse proxy and I got the following response from the auth server:
```
Bad request: unable to parse remote addr 2a01:x:x:x:x:x:x:x
```
Leading to:
```
$ docker pull registry.example.com/hello-world
Using default tag: latest
Error response from daemon: Head "https://registry.example.com/v2/hello-world/manifests/latest": error parsing HTTP 400 response body: invalid character 'B' looking for beginning of value: "Bad request: unable to parse remote addr 2a01:x:x:x:x:x:x:x\n"
```
My nginx configured that way:
```
proxy_pass          http://127.0.0.1:5001;
proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
```
And my YAML looking like this:
```yaml
server:
real_ip_header: …
```

Fix regexp parsing IPv6 without port indication in remote_addr

---

auth_server/go.mod
auth_server/main.go

**Reference:**
https://stackoverflow.com/questions/39320025
https://pkg.go.dev/net/http#Server.Shutdown

Remove httpdown

---

auth_server/main.go
auth_server/server/config.go
examples/reference.yml

Similar to Docker Registry, use combination of `addr` and `net` (supporting values `tcp` and `unix`). 
Requires #325

Support Unix Domain Sockets

---

auth_server/authn/data/oidc_auth.tmpl
auth_server/authn/oidc_auth.go
auth_server/server/config.go
examples/reference.yml

This PR adds the following features to OIDC auth:
- Configurable scope
- Labels from claims
- Configurable username claim
I've made the defaults the old static values so there shouldn't be any incompatibilities.

Add more configuration options for OIDC auth

---

chart/docker-auth/Chart.yaml
chart/docker-auth/templates/deployment.yaml
chart/docker-auth/values.yaml

Add option to add pod annotation and pod security constraint in helm charts
Change-Id: I1fc7d7d2ca60411439669921fb6a353bb001225a

Missing pod annotation and security constraint in helm chart

---

auth_server/server/config.go
auth_server/server/server.go

This PR moves the code to determine the signature algorithm for JWT to the loading part of the key/cert, where it previously resided in the part that signed every JWT.

Test for signature algorithm on startup/reload rather than per request

---

auth_server/main.go

Fixes https://github.com/cesanta/docker_auth/issues/379
Tested with `docker run --rm -ti  drwetter/testssl.sh -e --std 10.3.68.72:5001`

Use secure cipher suites for tls by default

---

auth_server/authn/github_auth.go
auth_server/authn/gitlab_auth.go
auth_server/authn/google_auth.go
auth_server/authn/oidc_auth.go
auth_server/authn/tokendb_gcs.go
auth_server/authn/tokendb_level.go
auth_server/authn/tokendb_redis.go
auth_server/server/config.go

The default bcrypt hashing cost can be quite problematic when serving many requests at once. Depending on token expiration times and other security considerations, lowering the cost can be a valid fix. This PR adds the `token_hash_cost` to all TokenDB configs (redis, GCS, LevelDB). Note that the level db config was a simple string previously, I had to change it to a struct with `{path: string, token_hash_cost: int}`.
Note that this PR is built on top of #374.

Add option to adjust bcrypt hashing cost

---

auth_server/authn/data/github_auth_result.tmpl

Prior to this, there was not an easy copy/paste line for people not using Docker. This addes example lines that can be copy/pasted for those of us who use Podman / Podman Desktop and containerd's nerdctl.
For context, nerdctl is the default way of interacting with containers run within Lima (https://lima-vm.io) and is how I run x86 containers on an Apple Silicon Mac.

Add additional examples logins to results page

---

auth_server/server/config.go
docs/auth-methods.md
examples/reference.yml

In order to ensure the project correctly validates authentication methods in the config file that can use a token db, this commit modifies the logic to ensure we check if all of the token methods are nil before outputting an error. Previously, if the local filesystem token db method was not nil and the other two (redis and google cloud storage) were nil, we would return an error and the config would be considered invalid.
Additionally, this commit documents the correct LevelDB settings for the config file. Prior to the addition of Bcrypt hashing cost, just using `token_db` was acceptable in the configuration along with a string representing the path. Given the swap to a struct instead of a string, we need to update documentation concerning this.

Fix LevelDB yaml unmarshall error and update documentation

---

auth_server/authn/github_auth.go
auth_server/authn/gitlab_auth.go
auth_server/authn/google_auth.go
auth_server/authn/oidc_auth.go
auth_server/server/config.go
docs/auth-methods.md
examples/reference.yml

Fix breaking changes changes made in 1.12 and leftovers:
*  `http_timeout: 10` became `http_timeout: "10s"` in the samples, otherwise it will be nanoseconds and impossible to do Google auth etc. Nothing mentioned in the changelog.
*  `token_db` config string became `level_token_db.path` in the samples. Nothing mentioned in the changelog.
*  Fixed config options checks when  `level_token_db.path`  was set but docker_auth still complaining it is not.
* Replace deprecated ioutil.ReadAll > io.ReadAll

Fix breaking changes changes made in 1.12 and leftovers

---

auth_server/server/config.go
auth_server/server/server.go
examples/reference.yml
examples/simple.yml

Fixes https://github.com/cesanta/docker_auth/issues/386.
This is a fairly quick and dirty fix, feel free to burn this PR down :)
As mentioned in that issue, the v3 version of the registry no longer supports `libtrust` key IDs. There are multiple alternative options to choose from, but the simplest one to implement for this project is using the [JWK thumbprint](https://www.rfc-editor.org/rfc/rfc7638.html) of the public key as the key ID instead.
For every certificate present in the `rootcertbundle` passed to the registry, it'll add the public key to the trusted keys identified by the JWK thumbprint: https://github.com/distribution/distribution/blob/63d3892315c817c931b88779399a8e9142899a8e/registry/auth/token/accesscontroller.go#L346-L348
So, if you pass this JWK thumbprint in the key ID …

Add support for registry v3 JWK thumbprint key ID format

---

chart/docker-auth/Chart.yaml
chart/docker-auth/README.md
chart/docker-auth/templates/configmap.yaml
chart/docker-auth/values.yaml

Fixes #409
Follows on from #401 to add the changes for disable_legacy_key_id to the helm chart configmap

Add disable_legacy_key_id to helm chart
